config/routes.rb
Rails.application.routes.draw do
  resources :pets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  helper_method :index

  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pet_path(@pet)
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def pet_params
    params.require(:pet).permit(:found, :name, :location, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/create.html.erb
<h1>Pets#create</h1>
<p>Find me in app/views/pets/create.html.erb</p>

app/views/pets/destroy.html.erb
<h1>Pets#destroy</h1>
<p>Find me in app/views/pets/destroy.html.erb</p>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/pets/index.html.erb
<h1>Lost Pets call 1-800 pets now</h1>
<ul>
  <% @pets.each do |pet|  %>
    <li>
      <h1><%= pet.name %></h1>
      <p><%= pet.location %></p>
    </li>
  <% end %>
</ul>

<%= link_to "I found a Pet!", new_pet_path %>

app/views/pets/new.html.erb
<h1>New Found Pet</h1>

<%= form_for(@pet) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :found %>
  <%= f.date_field :found %>

  <%= f.label :species %>
  <%= f.text_field :species %>

  <%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p><%= @pet.location %></p>
<p><%= @pet.species %></p>
<p><%= @pet.found %></p>

<%= link_to "Back to all pets", pets_path %>

app/views/pets/update.html.erb
<h1>Pets#update</h1>
<p>Find me in app/views/pets/update.html.erb</p>